deployment:
  tasks:
    - /bin/cp -R app/* /home/livejobs/public_html/app/
    - /bin/cp -R bootstrap/* /home/livejobs/public_html/bootstrap/
    - /bin/cp -R config/* /home/livejobs/public_html/config/
    - /bin/cp -R database/* /home/livejobs/public_html/database/
    - /bin/cp -R resources/* /home/livejobs/public_html/resources/
    - /bin/cp -R routes/* /home/livejobs/public_html/routes/
    - /bin/cp -R public/* /home/livejobs/public_html/
    - /bin/cp artisan /home/livejobs/public_html/
    - /bin/cp composer.json /home/livejobs/public_html/
    - /bin/cp composer.lock /home/livejobs/public_html/
    - /bin/cp package.json /home/livejobs/public_html/
    - /bin/cp package-lock.json /home/livejobs/public_html/
    - /bin/cp vite.config.js /home/livejobs/public_html/
    - /bin/cp postcss.config.js /home/livejobs/public_html/
    - /bin/cp tailwind.config.js /home/livejobs/public_html/
